# Generated by Django 3.1.7 on 2021-03-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя автора ')),
                ('email', models.EmailField(max_length=254, verbose_name='почта автора')),
                ('description', models.TextField(max_length=1000, verbose_name='текст записи')),
                ('status', models.CharField(blank=True, choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=15, null=True, verbose_name='Статус задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книгии',
                'db_table': 'books',
            },
        ),
    ]
