# Generated by Django 3.1.7 on 2021-03-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active',
                                   max_length=15, verbose_name='Статус задачи'),
        ),
    ]
